basic_settings:
  site_title: squiggly river
  favicon_image: images/icons/sparkle.svg

header_settings:
  logo_image: 
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'about'
      url: '/'
    - title: 'manifesto'
      url: '/manifesto'
    - title: 'meetups'
      url: '/meetups'
    - title: 'people'
      url:  '/people'
    # - title: 'archive'
    #   url: '/blog'

footer_settings:
  logo_image:
  logo_width: 
  tagline: The Squiggly River Games Collective is an arts collective and community founded in 2017 and run by <a href="https://twitter.com/erikaverkaaik">Erika Verkaaik</a> and <a href="https://twitter.com/BRKeogh">Brendan Keogh</a>. Our meetups take place on the lands of the Turrbul and Jagera nations. We pay our respects to their Elders; past and present. Sovereignty was never ceded.
hero_settings:
  background_image:

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: ''
  form_action: 
  confirmation_url: 
  email_subject: 
  send_button_text: ''

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/squigglyriver'
  itch-io_url: 'https://squigglyriver.itch.io/'
  discord_url: 'https://discord.gg/MrPzZXH'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#fffad4'
  # previous background yellow: #fdf5b1
  background_alt_color: '#f4f5f6'
  text_dark_color: '#202224'
  text_medium_color: '#6C7A89'
  text_light_color: '#648f47'
  accent_color: '#ff279a' 
  light_accent_color: '#66d4af'
  #accent_color: '#4C60E6'
  border_color: '#BCBDBF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Rubik:400,500,900|Mulish:400,700,900|Nunito:400,500,900" rel="stylesheet">'
  title_font: 'Nunito, sans-serif'
  body_font: 'Mulish, sans-serif'
  regular_weight: 400
  bold_weight: 900
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 900
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 900
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 900
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 72
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 700
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 700
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 30
    size_small: 28
    weight: 700
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 45
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 36
    size_small: 24
    size_tagline: 70
    weight_regular: 400
    weight_heavy: 900
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 42
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 18
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 30
    large_size: 38
    weight: 500
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0.4
  mark:
    weight: 400
    background_color: '#b1ff7e'

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: <script src="https://kit.fontawesome.com/59bb1f9a58.js" crossorigin="anonymous"></script>
  footer_js: ""